# Use an official Python image as the base image
FROM python:3.10.1-alpine

# Set the working directory in the container
WORKDIR /app

#cryptographをインストールするために必要なライブラリをインストール(時間かかる)
RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo pkgconfig

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files to the container
COPY . .

# Expose the default FastAPI port
EXPOSE 8000

# Run the command to start the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]